// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

// Package gatewaystub serves one canned gateway reply to the real SDK, so a
// test can assert on an error the SDK itself classified.
//
// It exists because the classifications that matter most here are unreachable
// any other way. ErrUnexpectedResponse — the marker separating an edge error
// page from a reply a Jamf service produced — is attached inside the SDK's
// unexported transport, so no exported constructor can produce a marked error
// and a hand-built one proves only that the provider agrees with itself. The
// same goes for the structured details the SDK lifts out of Jamf Pro's HTML
// error template.
//
// Deliberately untagged, unlike the rest of internal/testhelpers: these are
// unit tests, run by make test with no credentials and no estate.
package gatewaystub

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/jamf/jamfplatform-go-sdk/jamfplatform"
)

// Reply is one canned HTTP response for the stub to serve.
type Reply struct {
	ContentType string
	Body        string
	Status      int
}

// ErrorFrom drives a real SDK client against a stub serving reply, and returns
// the error the SDK produced.
//
// The path is a Pro read because every namespace reaches the same response
// handling; nothing here depends on which endpoint was called. Fails the test
// if the reply produced no error, since a test asserting on a classification
// has nothing to assert against.
//
// Retries are off. The SDK retries a 5xx, so a stub serving one spends fifteen
// seconds of `make test` re-proving the retry policy, which no test here is
// about. A classification does not depend on how many attempts preceded it.
func ErrorFrom(t *testing.T, reply Reply) error {
	t.Helper()

	const path = "/pro/v1/buildings/1"

	mux := http.NewServeMux()
	mux.HandleFunc("/auth/token", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(map[string]any{
			"access_token": "tok", "token_type": "Bearer", "expires_in": 3600,
		}); err != nil {
			t.Errorf("writing token response: %v", err)
		}
	})
	mux.HandleFunc(path, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", reply.ContentType)
		w.WriteHeader(reply.Status)
		if _, err := w.Write([]byte(reply.Body)); err != nil {
			t.Errorf("writing stub response: %v", err)
		}
	})

	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)

	client := jamfplatform.NewClient(srv.URL, "cid", "secret",
		jamfplatform.WithMinRequestInterval(0),
		jamfplatform.WithRetryPolicy(0, 0, 0),
		jamfplatform.WithTenantID("00000000-0000-0000-0000-000000000000"))

	var out map[string]any
	err := client.Transport().Do(context.Background(), http.MethodGet, path, nil, &out)
	if err == nil {
		t.Fatal("stub returned no error, so there is nothing to classify")
	}
	return err
}

// CloudFrontPage renders the body CloudFront served on the pro acceptance lane
// in CI run 34202213638, with the heading it prints for status.
//
// Kept verbatim rather than reduced to "some HTML" because the whole question
// these tests ask is whether the SDK separates this from Jamf Pro's own HTML
// error template, and a synthetic page proves nothing about a real one. Taking
// the heading as a parameter rather than hardcoding one keeps the page coherent
// with the status the stub serves alongside it: a fixed 404 heading under a 504
// reply is a combination CloudFront never produces, and a test reading that
// back cannot be checked against anything real.
func CloudFrontPage(heading string) string {
	return `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>` + heading + `</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
We can't connect to the server for this app or website at this time.
<PRE>
Generated by cloudfront (CloudFront) HTTP3 Server
Request ID: YUQftLkPfkIskyRXbupeY0_EQVmY6IDMo2vt6z6QJ5_B8U5HC3VzoQ&#x3D;&#x3D;
</PRE>
</BODY></HTML>`
}

// The headings CloudFront prints, matching the statuses observed in CI.
const (
	CloudFrontNotFound       = "404 ERROR"
	CloudFrontGatewayTimeout = "504 Gateway Timeout ERROR"
	CloudFrontBadGateway     = "502 Bad Gateway ERROR"
)

// NginxBlockPage is the other edge shape, and the one a WAF or IP allowlist
// serves: a 403 from nginx rather than a CDN failure page.
const NginxBlockPage = `<html>
<head><title>403 Forbidden</title></head>
<body><center><h1>403 Forbidden</h1></center><hr><center>nginx</center></body>
</html>`

// ClassicStatusPage is Jamf Pro's own error template, which every /proclassic
// path serves and which must never be read as an edge block.
const ClassicStatusPage = `<html><head><title>Status page</title></head>` +
	`<body><p>The server has not found anything matching the request URI</p></body></html>`
