// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

package progroups

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"github.com/jamf/jamfplatform-go-sdk/jamfplatform"

	"github.com/jamf/terraform-provider-jamfplatform/internal/common/helpers"
)

// The four codes these endpoints answer with that are worth naming for an
// operator. None of them is generated by the SDK — the group specs declare a bare
// ApiError with a free-form `code` string and enumerate no values — so they are
// literals here, checked one at a time rather than as a set, and pinned by
// enum_literals_test.go with Absent entries so a later SDK release that does
// generate them fails the build instead of leaving these behind.
const (
	// codeHasDependencies is the refusal to delete a group something is scoped
	// to. Its description names the dependents.
	codeHasDependencies = "HAS_DEPENDENCIES"
	// codeInvalidDevice covers both a device that does not exist and a device
	// outside the group's site. The server does not distinguish them.
	codeInvalidDevice = "INVALID_DEVICE"
	// codeDuplicateField is a group name already in use.
	codeDuplicateField = "DUPLICATE_FIELD"
	// codeInvalidPrivilege is the site refusal: absent on a mobile write, or an
	// id naming a site the integration cannot reach.
	codeInvalidPrivilege = "INVALID_PRIVILEGE"
)

// hasCode reports whether err is a Jamf API error carrying code in one of its
// structured error details.
//
// It reads the decoded details rather than matching a substring of the rendered
// error, because a code's own spelling also appears in free text: the delete
// refusal's description names the dependents, and a group an operator called
// "INVALID_DEVICE" would otherwise classify every failure that mentioned it.
// The group endpoints always populate the details when they report a code at
// all — the one shape that does not is the 500 with an empty errors array, which
// carries no code to match anyway.
func hasCode(err error, code string) bool {
	apiErr := jamfplatform.AsAPIError(err)
	if apiErr == nil {
		return false
	}
	for _, detail := range apiErr.Errors {
		if strings.EqualFold(detail.Code, code) {
			return true
		}
	}
	return false
}

// IsDependencyConflict reports whether err is Jamf Pro refusing to delete a group
// because something is still scoped to it.
func IsDependencyConflict(err error) bool { return hasCode(err, codeHasDependencies) }

// IsInvalidDevice reports whether err is Jamf Pro rejecting a static group's
// membership list.
func IsInvalidDevice(err error) bool { return hasCode(err, codeInvalidDevice) }

// IsDuplicateName reports whether err is Jamf Pro rejecting a group name that is
// already in use.
func IsDuplicateName(err error) bool { return hasCode(err, codeDuplicateField) }

// IsSiteRefused reports whether err is Jamf Pro refusing the site on a write.
func IsSiteRefused(err error) bool { return hasCode(err, codeInvalidPrivilege) }

// DeleteDiagnostics turns a failed group delete into diagnostics, naming the
// dependency case.
//
// Jamf Pro answers 422 HAS_DEPENDENCIES while anything is still scoped to the
// group, and its description lists the dependents by name, so the detail carries
// the server's own list rather than paraphrasing it.
//
// This refusal is PERMANENT. It is not the propagation-blocked shape
// jamfplatform_device_group re-issues its delete for: nothing is catching up in
// the background, and the object will refuse for as long as the reference exists.
// Polling it would only spend the timeout, so callers translate and return.
//
// The Terraform consequence is worth stating to the operator, because it is an
// ordering trap rather than a provider fault: dropping a group from a policy's
// scope and destroying the group in one apply can let Terraform sequence the
// destroy first, since the configuration edge is already gone from the new graph.
func DeleteDiagnostics(err error, label string) diag.Diagnostics {
	var diags diag.Diagnostics
	if IsDependencyConflict(err) {
		diags.AddError(
			fmt.Sprintf("Cannot delete this %s while something is scoped to it", label),
			"Jamf Pro refused the deletion and named what still references the group: "+helpers.APIErrorDetail(err)+
				"\n\nRemove the group from everything listed, apply that, then destroy the group. Doing both in one apply can order the destroy first, because the configuration no longer records that anything depended on it.",
		)
		return diags
	}
	diags.AddError(fmt.Sprintf("Error deleting Jamf Pro %s", label), helpers.APIErrorDetail(err))
	return diags
}

// WriteDiagnostics turns a failed group create or update into diagnostics,
// naming the three cases Jamf Pro reports with a code but describes only
// generically.
//
// membersPath anchors the membership case; pass a null path on a smart group,
// which has no membership attribute and cannot raise it.
func WriteDiagnostics(err error, label string, sitePath, membersPath path.Path) diag.Diagnostics {
	var diags diag.Diagnostics
	switch {
	case IsInvalidDevice(err):
		diags.Append(atAttribute(
			membersPath,
			"Jamf Pro rejected one or more members of this group",
			"Jamf Pro reported that at least one of the listed devices cannot be a member, and does not say which one or why. Three causes produce this same answer:"+
				"\n\n1. The device does not exist."+
				"\n2. The group belongs to a site and the device is not assigned to that same site. A group in a site holds only devices in it."+
				"\n3. For a computer group, the computer is not managed. Jamf Pro refuses an unmanaged computer as a static group member."+
				"\n\nJamf Pro's response: "+helpers.APIErrorDetail(err),
		))
	case IsDuplicateName(err):
		diags.AddError(
			fmt.Sprintf("A %s with this name already exists", label),
			"Jamf Pro requires a group name to be unique. To bring the existing group under Terraform management instead of creating another, import it."+
				"\n\nJamf Pro's response: "+helpers.APIErrorDetail(err),
		)
	case IsSiteRefused(err):
		diags.Append(atAttribute(
			sitePath,
			"Jamf Pro refused the site for this group",
			"Jamf Pro reports this as a permissions failure, which is misleading: it answers the same way for a site that does not exist and for one the API integration cannot reach. Check that the site id exists, and that the integration has access to it."+
				"\n\nJamf Pro's response: "+helpers.APIErrorDetail(err),
		))
	default:
		diags.AddError(fmt.Sprintf("Error writing Jamf Pro %s", label), helpers.APIErrorDetail(err))
	}
	return diags
}

// atAttribute anchors an error diagnostic to attr, or leaves it unanchored when
// attr is the zero path.
//
// A smart group has no membership attribute and a caller passes the zero value
// for it. An empty path renders as the resource root, which would put a
// membership message on the resource itself; returning a plain diagnostic
// instead keeps the message without implying it belongs to an attribute that is
// not in the schema.
func atAttribute(attr path.Path, summary, detail string) diag.Diagnostic {
	if attr.Equal(path.Empty()) {
		return diag.NewErrorDiagnostic(summary, detail)
	}
	return diag.NewAttributeErrorDiagnostic(attr, summary, detail)
}
