// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

package mobile_device_invitation

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform/proclassic"

	"github.com/jamf/terraform-provider-jamfplatform/internal/common/helpers"
	"github.com/jamf/terraform-provider-jamfplatform/internal/providerdata"
)

// MobileDeviceInvitationDataSource implements the Terraform data source for Jamf
// Pro mobile device invitations. Selection is by numeric `id` OR by the
// server-minted `invitation` code (the UI "Invitation ID") — exactly one of the
// two. There is no name lookup because invitations carry no name on the wire.
type MobileDeviceInvitationDataSource struct {
	client *proclassic.Client
}

var (
	_ datasource.DataSource                     = &MobileDeviceInvitationDataSource{}
	_ datasource.DataSourceWithConfigure        = &MobileDeviceInvitationDataSource{}
	_ datasource.DataSourceWithConfigValidators = &MobileDeviceInvitationDataSource{}
)

// NewMobileDeviceInvitationDataSource returns a new instance of
// MobileDeviceInvitationDataSource.
func NewMobileDeviceInvitationDataSource() datasource.DataSource {
	return &MobileDeviceInvitationDataSource{}
}

// Metadata sets the data source type name for the Terraform provider.
func (d *MobileDeviceInvitationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pro_mobile_device_invitation"
}

// Schema returns the data source schema.
func (d *MobileDeviceInvitationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a Jamf Pro mobile device enrollment invitation by numeric `id` or by its Jamf Pro-generated `invitation` code (the admin UI \"Invitation ID\"). Exactly one of `id` or `invitation` must be supplied." + dataSourcePrivileges,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Numeric mobile device invitation ID. Mutually exclusive with `invitation`.",
				Optional:            true,
				Computed:            true,
			},
			"invitation": schema.StringAttribute{
				MarkdownDescription: "Invitation code generated by Jamf Pro (the admin UI \"Invitation ID\"). Mutually exclusive with `id`.",
				Optional:            true,
				Computed:            true,
			},
			"invitation_type":               schema.StringAttribute{MarkdownDescription: "Invitation delivery type.", Computed: true},
			"expiration_date":               schema.StringAttribute{MarkdownDescription: "Invitation expiration (`Unlimited` or `yyyy-MM-dd HH:mm:ss`).", Computed: true},
			"expiration_date_epoch":         schema.StringAttribute{MarkdownDescription: "Expiration date as epoch milliseconds.", Computed: true},
			"expiration_date_utc":           schema.StringAttribute{MarkdownDescription: "Expiration date in UTC.", Computed: true},
			"enroll_into_site_id":           schema.StringAttribute{MarkdownDescription: "Jamf Pro site ID the enrolled mobile device is assigned to (`-1` when none).", Computed: true},
			"enroll_into_site_name":         schema.StringAttribute{MarkdownDescription: "Display name of the site the enrolled mobile device is assigned to (`NONE` when none).", Computed: true},
			"keep_existing_site_membership": schema.BoolAttribute{MarkdownDescription: "Whether an enrolling mobile device keeps its existing site membership.", Computed: true},
			"multiple_uses_allowed":         schema.BoolAttribute{MarkdownDescription: "Whether the invitation may be used for more than one mobile device.", Computed: true},
			"require_login":                 schema.BoolAttribute{MarkdownDescription: "Whether the enrolling user must authenticate (the admin UI \"Require Login\").", Computed: true},
			"subject":                       schema.StringAttribute{MarkdownDescription: "Subject line of the enrollment email.", Computed: true},
			"message":                       schema.StringAttribute{MarkdownDescription: "Body of the enrollment email.", Computed: true},
			"reply_to":                      schema.StringAttribute{MarkdownDescription: "Reply-to address for the enrollment email.", Computed: true},
			"sent_from":                     schema.StringAttribute{MarkdownDescription: "From address for the enrollment email.", Computed: true},
			"sent_to":                       schema.StringAttribute{MarkdownDescription: "Recipient address for the enrollment email.", Computed: true},
			"username":                      schema.StringAttribute{MarkdownDescription: "Username associated with the invitation.", Computed: true},
			"target_ios":                    schema.StringAttribute{MarkdownDescription: "Target iOS version for the invitation.", Computed: true},
			"last_action":                   schema.StringAttribute{MarkdownDescription: "Last action recorded for the invitation.", Computed: true},
			"date_sent":                     schema.StringAttribute{MarkdownDescription: "Date the invitation email was sent.", Computed: true},
			"date_sent_utc":                 schema.StringAttribute{MarkdownDescription: "Date the invitation email was sent, in UTC.", Computed: true},
			"date_sent_epoch":               schema.StringAttribute{MarkdownDescription: "Date the invitation email was sent, as epoch milliseconds.", Computed: true},
			"timeouts":                      timeouts.Attributes(ctx),
		},
	}
}

// ConfigValidators enforces that exactly one of id / invitation is supplied.
func (d *MobileDeviceInvitationDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.ExactlyOneOf(
			path.MatchRoot("id"),
			path.MatchRoot("invitation"),
		),
	}
}

// Configure wires the Jamf ProClassic client into the data source via the
// shared providerdata.ConfigureProClassic helper.
func (d *MobileDeviceInvitationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := providerdata.ConfigureProClassic(ctx, req.ProviderData, minJamfProVersion, "jamfplatform_pro_mobile_device_invitation")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	d.client = client
}

// Read fetches a mobile device invitation by ID or by invitation code and
// populates Terraform state.
func (d *MobileDeviceInvitationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	if d.client == nil {
		resp.Diagnostics.AddError(
			"Provider not configured",
			"The provider client was not configured. Please ensure the provider block is set up correctly.",
		)
		return
	}

	var data MobileDeviceInvitationDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, timeoutDiags := helpers.ResolveTimeout(ctx, data.Timeouts.IsNull(), data.Timeouts.IsUnknown(), defaultReadTimeout, data.Timeouts.Read)
	resp.Diagnostics.Append(timeoutDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	readCtx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	var (
		got *proclassic.MobileDeviceInvitation
		err error
	)
	switch {
	case !data.ID.IsNull() && data.ID.ValueString() != "":
		got, err = d.client.GetMobileDeviceInvitationByID(readCtx, data.ID.ValueString())
	case !data.Invitation.IsNull() && data.Invitation.ValueString() != "":
		got, err = d.client.GetMobileDeviceInvitationByInvitation(readCtx, data.Invitation.ValueString())
	default:
		resp.Diagnostics.AddError("Missing mobile device invitation selector", "Exactly one of id or invitation must be supplied.")
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to find Jamf Pro mobile device invitation", helpers.APIErrorDetail(err))
		return
	}
	assignMobileDeviceInvitationDataSourceModel(&data, got)

	tflog.Trace(ctx, "read Jamf Pro mobile device invitation data source", map[string]any{"id": data.ID.ValueString(), "invitation": data.Invitation.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
