// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

// Package mobile_device_invitation implements the
// jamfplatform_pro_mobile_device_invitation resource, data source, and list
// resource backed by the Jamf ProClassic /mobiledeviceinvitations API.
package mobile_device_invitation

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform/proclassic"

	"github.com/jamf/terraform-provider-jamfplatform/internal/providerdata"
)

// minJamfProVersion is the minimum Jamf Pro tenant version required by this
// resource. Empty: the classic /mobiledeviceinvitations endpoint predates the
// provider's overall floor. The provider-level advisory still fires through
// providerdata.ConfigureProClassic when the tenant is below
// ProviderMinJamfProVersion.
const minJamfProVersion = ""

// MobileDeviceInvitationResource implements the Terraform resource for Jamf Pro
// mobile device enrollment invitations.
type MobileDeviceInvitationResource struct {
	client *proclassic.Client
}

var (
	_ resource.Resource                = &MobileDeviceInvitationResource{}
	_ resource.ResourceWithImportState = &MobileDeviceInvitationResource{}
	_ resource.ResourceWithIdentity    = &MobileDeviceInvitationResource{}
)

const (
	defaultCreateTimeout = 60 * time.Second
	defaultReadTimeout   = 60 * time.Second
	defaultUpdateTimeout = 60 * time.Second
	defaultDeleteTimeout = 60 * time.Second
)

// NewMobileDeviceInvitationResource returns a new instance of
// MobileDeviceInvitationResource.
func NewMobileDeviceInvitationResource() resource.Resource {
	return &MobileDeviceInvitationResource{}
}

// Metadata sets the resource type name for the Terraform provider.
func (r *MobileDeviceInvitationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pro_mobile_device_invitation"
}

// IdentitySchema defines the identifier used for import and list results.
func (r *MobileDeviceInvitationResource) IdentitySchema(ctx context.Context, req resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"id": identityschema.StringAttribute{
				Description:       "Jamf Pro mobile device invitation numeric ID used to uniquely reference the invitation.",
				RequiredForImport: true,
			},
		},
	}
}

// Schema returns the Terraform schema for the mobile device invitation resource.
//
// Every user-settable attribute is RequiresReplace: the /mobiledeviceinvitations
// endpoint is create + delete only (the SDK's update function targets a PUT the
// server rejects with `409 "Put is not supported"`), so a change to any input
// forces a destroy + recreate, which mints a new `invitation` code.
func (r *MobileDeviceInvitationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Jamf Pro mobile device enrollment invitation: a single-use or multiple-use token for the user-initiated enrollment of mobile devices, carrying a site assignment and an expiration, optionally delivered by email and optionally requiring login. An invitation cannot be updated in place. Changing any attribute forces Terraform to destroy and recreate it, which mints a new `invitation` code." + resourcePrivileges,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Numeric mobile device invitation ID assigned by Jamf Pro. This is the Terraform state ID and the import key.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invitation": schema.StringAttribute{
				MarkdownDescription: "Invitation code generated by Jamf Pro (the admin UI's \"Invitation ID\"); a large decimal value, not user-settable. A new code is generated each time the invitation is created, so it changes whenever the resource is replaced.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invitation_type": schema.StringAttribute{
				MarkdownDescription: "Invitation delivery type. One of `USER_INITIATED_URL` or `USER_INITIATED_EMAIL`. Changing this forces replacement.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf(validInvitationTypes...),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"expiration_date": schema.StringAttribute{
				MarkdownDescription: "Invitation expiration. Either the literal `Unlimited` (never expires) or a wall-clock timestamp in the format `yyyy-MM-dd HH:mm:ss` (e.g. `2026-12-31 23:59:00`), interpreted in the Jamf Pro server's timezone. Jamf Pro may normalise a finite timestamp by up to a minute; the provider preserves your configured value, so that does not surface as drift. Omit to let Jamf Pro assign the expiration, which is then reflected in state. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"expiration_date_epoch": schema.StringAttribute{
				MarkdownDescription: "Expiration date as epoch milliseconds, returned by Jamf Pro. `0` when the expiration is `Unlimited`.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"expiration_date_utc": schema.StringAttribute{
				MarkdownDescription: "Expiration date in UTC, returned by Jamf Pro. `Unlimited` when the invitation never expires.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enroll_into_site_id": schema.StringAttribute{
				MarkdownDescription: "**\"Site\"** in the Jamf Pro admin UI. The site the enrolled mobile device is assigned to, given as a Jamf Pro site ID. Use `-1` for \"None\". Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enroll_into_site_name": schema.StringAttribute{
				// No UseStateForUnknown: enroll_into_site_name is derived from
				// enroll_into_site_id, so it must go Unknown (not pin the stale
				// value) whenever the id changes, or an id change trips the
				// post-apply consistency check.
				MarkdownDescription: "Site display name. Returned by Jamf Pro; not user-settable.",
				Computed:            true,
			},
			"keep_existing_site_membership": schema.BoolAttribute{
				MarkdownDescription: "The admin UI's \"Use existing site membership, if applicable\". When true, an enrolling mobile device that already belongs to a site keeps that membership. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"multiple_uses_allowed": schema.BoolAttribute{
				MarkdownDescription: "Whether the invitation may be used to enrol more than one mobile device. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"require_login": schema.BoolAttribute{
				MarkdownDescription: "The admin UI's \"Require Login\". When true, the enrolling user must authenticate before completing enrollment. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"subject": schema.StringAttribute{
				MarkdownDescription: "Subject line of the enrollment email. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"message": schema.StringAttribute{
				MarkdownDescription: "Body of the enrollment email. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"reply_to": schema.StringAttribute{
				MarkdownDescription: "Reply-to address for the enrollment email. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"sent_from": schema.StringAttribute{
				MarkdownDescription: "From address for the enrollment email. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"sent_to": schema.StringAttribute{
				MarkdownDescription: "Recipient address for the enrollment email. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username associated with the invitation. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"target_ios": schema.StringAttribute{
				MarkdownDescription: "Target iOS version for the invitation (e.g. `iOS 4`). Jamf Pro applies a default of `iOS 4` when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"last_action": schema.StringAttribute{
				MarkdownDescription: "Last action recorded for the invitation, returned by Jamf Pro.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"date_sent": schema.StringAttribute{
				MarkdownDescription: "Date the invitation email was sent, returned by Jamf Pro.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"date_sent_utc": schema.StringAttribute{
				MarkdownDescription: "Date the invitation email was sent, in UTC, returned by Jamf Pro.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"date_sent_epoch": schema.StringAttribute{
				MarkdownDescription: "Date the invitation email was sent, as epoch milliseconds, returned by Jamf Pro.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

// Configure wires the Jamf ProClassic client into the resource via the shared
// providerdata.ConfigureProClassic helper.
func (r *MobileDeviceInvitationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := providerdata.ConfigureProClassic(ctx, req.ProviderData, minJamfProVersion, "jamfplatform_pro_mobile_device_invitation")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.client = client
}

// ImportState handles import by the Jamf Pro mobile device invitation numeric ID.
func (r *MobileDeviceInvitationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
