// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

// Package sso_failover_url implements the jamfplatform_pro_sso_failover_url
// singleton resource and data source. The resource wraps the Jamf Pro
// failover URL — a tenant-scoped IdP-bypass URL that admins can hand to
// users when the upstream SSO IdP is unreachable. The URL is regenerated by
// changing `regeneration_trigger` (any change forces a POST /generate).
package sso_failover_url

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform/pro"

	"github.com/jamf/terraform-provider-jamfplatform/internal/common/helpers"
	"github.com/jamf/terraform-provider-jamfplatform/internal/providerdata"
)

// minJamfProVersion gates the resource to a minimum Jamf Pro tenant
// version. Empty: /v1/sso/failover ships at the provider's overall floor.
const minJamfProVersion = ""

// SsoFailoverURLResource implements the failover URL singleton.
type SsoFailoverURLResource struct {
	client *pro.Client
}

var _ resource.Resource = &SsoFailoverURLResource{}
var _ resource.ResourceWithImportState = &SsoFailoverURLResource{}
var _ resource.ResourceWithIdentity = &SsoFailoverURLResource{}

const (
	defaultCreateTimeout = 60 * time.Second
	defaultReadTimeout   = 60 * time.Second
	defaultUpdateTimeout = 60 * time.Second
	defaultDeleteTimeout = 60 * time.Second
)

// NewSsoFailoverURLResource constructs a new SsoFailoverURLResource.
func NewSsoFailoverURLResource() resource.Resource {
	return &SsoFailoverURLResource{}
}

// Metadata sets the resource type name.
func (r *SsoFailoverURLResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pro_sso_failover_url"
}

// IdentitySchema declares the singleton import identifier.
func (r *SsoFailoverURLResource) IdentitySchema(ctx context.Context, req resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"id": identityschema.StringAttribute{
				Description:       "Fixed singleton identifier. Always \"singleton\".",
				RequiredForImport: true,
			},
		},
	}
}

// Schema returns the resource schema.
func (r *SsoFailoverURLResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the Jamf Pro **SSO failover URL**, a tenant-scoped sign-in URL administrators can use when the upstream SSO identity provider is unreachable.\n\n" +
			"The URL is rotated by changing `regeneration_trigger`. Any change to that attribute makes the next apply regenerate the URL.\n\n" +
			"Destroy is state-only. `terraform destroy` removes the resource from Terraform state but leaves the failover URL live on the tenant, because Jamf Pro offers no way to clear or disable it.\n\n" +
			"Import with `terraform import jamfplatform_pro_sso_failover_url.<name> singleton`." + resourcePrivileges,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Fixed singleton identifier. Always `singleton`.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"regeneration_trigger": schema.StringAttribute{
				MarkdownDescription: "Rotation trigger. Set to any free-text value, such as a version label or timestamp; changing it on a subsequent apply produces a new `failover_url`. Omit it to leave the current URL untouched. Jamf Pro never returns this value, so it stays absent on read and an existing failover URL can be imported without supplying it.",
				Optional:            true,
			},
			"failover_url": schema.StringAttribute{
				MarkdownDescription: "Current failover URL. Treat it as a credential: anyone holding the URL can bypass SSO to sign in.",
				Computed:            true,
				Sensitive:           true,
			},
			"generation_time": schema.Int64Attribute{
				MarkdownDescription: "Generation timestamp in Unix milliseconds.",
				Computed:            true,
			},
			"generation_time_utc": schema.StringAttribute{
				MarkdownDescription: "Generation timestamp formatted as RFC3339 UTC.",
				Computed:            true,
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

// Configure wires the Jamf Pro client.
func (r *SsoFailoverURLResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := providerdata.ConfigurePro(ctx, req.ProviderData, minJamfProVersion, "jamfplatform_pro_sso_failover_url")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.client = client
}

// ImportState handles import for the singleton.
func (r *SsoFailoverURLResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	helpers.ImportSingletonState(ctx, req, resp, "jamfplatform_pro_sso_failover_url")
}
