// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

package computer_invitation

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform/proclassic"

	"github.com/jamf/terraform-provider-jamfplatform/internal/common/helpers"
	"github.com/jamf/terraform-provider-jamfplatform/internal/providerdata"
)

// ComputerInvitationDataSource implements the Terraform data source for Jamf Pro
// computer invitations. Selection is by numeric `id` OR by the server-minted
// `invitation` code (the UI "Invitation ID") — exactly one of the two. There is
// no name lookup because invitations carry no name on the wire.
type ComputerInvitationDataSource struct {
	client *proclassic.Client
}

var (
	_ datasource.DataSource                     = &ComputerInvitationDataSource{}
	_ datasource.DataSourceWithConfigure        = &ComputerInvitationDataSource{}
	_ datasource.DataSourceWithConfigValidators = &ComputerInvitationDataSource{}
)

// NewComputerInvitationDataSource returns a new instance of
// ComputerInvitationDataSource.
func NewComputerInvitationDataSource() datasource.DataSource {
	return &ComputerInvitationDataSource{}
}

// Metadata sets the data source type name for the Terraform provider.
func (d *ComputerInvitationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pro_computer_invitation"
}

// Schema returns the data source schema.
func (d *ComputerInvitationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a Jamf Pro computer enrollment invitation by numeric `id` or by its Jamf Pro-generated `invitation` code (the admin UI \"Invitation ID\"). Exactly one of `id` or `invitation` must be supplied." + dataSourcePrivileges,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Numeric computer invitation ID. Mutually exclusive with `invitation`.",
				Optional:            true,
				Computed:            true,
			},
			"invitation": schema.StringAttribute{
				MarkdownDescription: "Invitation code generated by Jamf Pro (the admin UI \"Invitation ID\"). Mutually exclusive with `id`.",
				Optional:            true,
				Computed:            true,
			},
			"invitation_type":                  schema.StringAttribute{MarkdownDescription: "Invitation delivery type.", Computed: true},
			"expiration_date":                  schema.StringAttribute{MarkdownDescription: "Invitation expiration (`Unlimited` or `yyyy-MM-dd HH:mm:ss`).", Computed: true},
			"expiration_date_epoch":            schema.StringAttribute{MarkdownDescription: "Expiration date as epoch milliseconds.", Computed: true},
			"expiration_date_utc":              schema.StringAttribute{MarkdownDescription: "Expiration date in UTC.", Computed: true},
			"enroll_into_site_id":              schema.StringAttribute{MarkdownDescription: "Jamf Pro site ID the enrolled computer is assigned to (`-1` when none).", Computed: true},
			"enroll_into_site_name":            schema.StringAttribute{MarkdownDescription: "Display name of the site the enrolled computer is assigned to (`NONE` when none).", Computed: true},
			"keep_existing_site_membership":    schema.BoolAttribute{MarkdownDescription: "Whether an enrolling computer keeps its existing site membership.", Computed: true},
			"multiple_uses_allowed":            schema.BoolAttribute{MarkdownDescription: "Whether the invitation may be used for more than one computer.", Computed: true},
			"create_account_if_does_not_exist": schema.BoolAttribute{MarkdownDescription: "Whether the SSH management account is created if it does not exist.", Computed: true},
			"hide_account":                     schema.BoolAttribute{MarkdownDescription: "Whether the SSH management account is hidden.", Computed: true},
			"lock_down_ssh":                    schema.BoolAttribute{MarkdownDescription: "Whether SSH is restricted to the management account.", Computed: true},
			"ssh_username":                     schema.StringAttribute{MarkdownDescription: "Username of the SSH management account.", Computed: true},
			"invitation_status":                schema.StringAttribute{MarkdownDescription: "Current status of the invitation.", Computed: true},
			"times_used":                       schema.Int64Attribute{MarkdownDescription: "Number of times the invitation has been used.", Computed: true},
			"invited_user_uuid":                schema.StringAttribute{MarkdownDescription: "UUID of the invited user.", Computed: true},
			"timeouts":                         timeouts.Attributes(ctx),
		},
	}
}

// ConfigValidators enforces that exactly one of id / invitation is supplied.
func (d *ComputerInvitationDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.ExactlyOneOf(
			path.MatchRoot("id"),
			path.MatchRoot("invitation"),
		),
	}
}

// Configure wires the Jamf ProClassic client into the data source via the
// shared providerdata.ConfigureProClassic helper.
func (d *ComputerInvitationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := providerdata.ConfigureProClassic(ctx, req.ProviderData, minJamfProVersion, "jamfplatform_pro_computer_invitation")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	d.client = client
}

// Read fetches a computer invitation by ID or by invitation code and populates
// Terraform state.
func (d *ComputerInvitationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	if d.client == nil {
		resp.Diagnostics.AddError(
			"Provider not configured",
			"The provider client was not configured. Please ensure the provider block is set up correctly.",
		)
		return
	}

	var data ComputerInvitationDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, timeoutDiags := helpers.ResolveTimeout(ctx, data.Timeouts.IsNull(), data.Timeouts.IsUnknown(), defaultReadTimeout, data.Timeouts.Read)
	resp.Diagnostics.Append(timeoutDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	readCtx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	var (
		got *proclassic.ComputerInvitation
		err error
	)
	switch {
	case !data.ID.IsNull() && data.ID.ValueString() != "":
		got, err = d.client.GetComputerInvitationByID(readCtx, data.ID.ValueString())
	case !data.Invitation.IsNull() && data.Invitation.ValueString() != "":
		got, err = d.client.GetComputerInvitationByInvitation(readCtx, data.Invitation.ValueString())
	default:
		resp.Diagnostics.AddError("Missing computer invitation selector", "Exactly one of id or invitation must be supplied.")
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to find Jamf Pro computer invitation", helpers.APIErrorDetail(err))
		return
	}
	assignComputerInvitationDataSourceModel(&data, got)

	tflog.Trace(ctx, "read Jamf Pro computer invitation data source", map[string]any{"id": data.ID.ValueString(), "invitation": data.Invitation.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
