// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

// Package computer_invitation implements the jamfplatform_pro_computer_invitation
// resource, data source, and list resource backed by the Jamf ProClassic
// /computerinvitations API.
package computer_invitation

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform/proclassic"

	"github.com/jamf/terraform-provider-jamfplatform/internal/providerdata"
)

// minJamfProVersion is the minimum Jamf Pro tenant version required by this
// resource. Empty: the classic /computerinvitations endpoint predates the
// provider's overall floor. The provider-level advisory still fires through
// providerdata.ConfigureProClassic when the tenant is below
// ProviderMinJamfProVersion.
const minJamfProVersion = ""

// ComputerInvitationResource implements the Terraform resource for Jamf Pro
// computer enrollment invitations.
type ComputerInvitationResource struct {
	client *proclassic.Client
}

var (
	_ resource.Resource                = &ComputerInvitationResource{}
	_ resource.ResourceWithImportState = &ComputerInvitationResource{}
	_ resource.ResourceWithIdentity    = &ComputerInvitationResource{}
)

const (
	defaultCreateTimeout = 60 * time.Second
	defaultReadTimeout   = 60 * time.Second
	defaultUpdateTimeout = 60 * time.Second
	defaultDeleteTimeout = 60 * time.Second
)

// NewComputerInvitationResource returns a new instance of
// ComputerInvitationResource.
func NewComputerInvitationResource() resource.Resource {
	return &ComputerInvitationResource{}
}

// Metadata sets the resource type name for the Terraform provider.
func (r *ComputerInvitationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pro_computer_invitation"
}

// IdentitySchema defines the identifier used for import and list results.
func (r *ComputerInvitationResource) IdentitySchema(ctx context.Context, req resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"id": identityschema.StringAttribute{
				Description:       "Jamf Pro computer invitation numeric ID used to uniquely reference the invitation.",
				RequiredForImport: true,
			},
		},
	}
}

// Schema returns the Terraform schema for the computer invitation resource.
//
// Every user-settable attribute is RequiresReplace: the /computerinvitations
// endpoint is create + delete only (no update route on the wire), so a change
// to any input forces a destroy + recreate, which mints a new `invitation`
// code.
func (r *ComputerInvitationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Jamf Pro computer enrollment invitation. A computer invitation is an enrollment token for the user-initiated enrollment of Mac computers, single-use or multiple-use, carrying an SSH management account to provision on the target machine and an expiration. The invitation **cannot be updated in place**: changing any attribute forces Terraform to destroy and recreate it, which mints a new `invitation` code. The plaintext `ssh_password` is a Terraform `WriteOnly` attribute, sent to Jamf Pro when the invitation is created but never persisted in Terraform state." + resourcePrivileges,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Numeric computer invitation ID assigned by Jamf Pro. This is the Terraform state ID and the import key.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invitation": schema.StringAttribute{
				MarkdownDescription: "Invitation code generated by Jamf Pro (the admin UI's \"Invitation ID\"); a large decimal value, not user-settable. A new code is generated each time the invitation is created, so it changes whenever the resource is replaced.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invitation_type": schema.StringAttribute{
				MarkdownDescription: "Invitation delivery type. One of " + markdownValueList(validInvitationTypes) + ". `USER_INITIATED_URL` and `USER_INITIATED_EMAIL` are created through this resource; `DEP_CUSTOM_ENROLL` is minted by Automated Device Enrollment and is accepted so an imported ADE invitation validates, but Jamf Pro rejects an attempt to create one from scratch. Changing this forces replacement.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf(validInvitationTypes...),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"expiration_date": schema.StringAttribute{
				MarkdownDescription: "Invitation expiration. Either the literal `Unlimited`, which never expires, or a wall-clock timestamp in the format `yyyy-MM-dd HH:mm:ss` such as `2026-12-31 23:59:00`, read in the Jamf Pro server's timezone. Jamf Pro may normalise a finite timestamp by up to a minute; the provider preserves your configured value, so that does not surface as drift. Omit the attribute to let Jamf Pro assign the expiration, which is then reflected in state. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"expiration_date_epoch": schema.StringAttribute{
				MarkdownDescription: "Expiration date as epoch milliseconds, returned by Jamf Pro. `0` when the expiration is `Unlimited`.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"expiration_date_utc": schema.StringAttribute{
				MarkdownDescription: "Expiration date in UTC, returned by Jamf Pro. `Unlimited` when the invitation never expires.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enroll_into_site_id": schema.StringAttribute{
				MarkdownDescription: "**\"Site\"** in the Jamf Pro admin UI. The site the enrolled computer is assigned to, given as a Jamf Pro site ID. Use `-1` for \"None\". Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseNonNullStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enroll_into_site_name": schema.StringAttribute{
				// No UseStateForUnknown: enroll_into_site_name is derived from
				// enroll_into_site_id, so it must go Unknown (not pin the stale
				// value) whenever the id changes, or an id change trips the
				// post-apply consistency check.
				MarkdownDescription: "Site display name. Returned by Jamf Pro; not user-settable.",
				Computed:            true,
			},
			"keep_existing_site_membership": schema.BoolAttribute{
				MarkdownDescription: "The admin UI's \"Use existing site membership, if applicable\". When true, an enrolling computer that already belongs to a site keeps that membership. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"multiple_uses_allowed": schema.BoolAttribute{
				MarkdownDescription: "Whether the invitation may be used to enrol more than one computer. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"create_account_if_does_not_exist": schema.BoolAttribute{
				MarkdownDescription: "Create the SSH management account on the enrolled computer if it does not already exist. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"hide_account": schema.BoolAttribute{
				MarkdownDescription: "Hide the SSH management account from the macOS login window and Users & Groups. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"lock_down_ssh": schema.BoolAttribute{
				MarkdownDescription: "Restrict SSH (Remote Login) access to the management account only on the enrolled computer. Jamf Pro applies a default when omitted. Changing this forces replacement.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
					boolplanmodifier.RequiresReplace(),
				},
			},
			"ssh_username": schema.StringAttribute{
				// Wire-probed 2026-06-26: /computerinvitations rejects a create with
				// the <ssh_username> element absent (HTTP 500) for both invitation
				// types, but accepts it empty. Hence Required (the element must be
				// present) with no min-length validator — empty is valid, and a
				// DEP-created invitation reads back empty.
				MarkdownDescription: "Username of the SSH management account to provision on the enrolled computer. Required by Jamf Pro on every computer invitation, but may be empty. Changing this forces replacement.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"ssh_password": schema.StringAttribute{
				MarkdownDescription: "Plaintext password for the SSH management account. `WriteOnly`: sent to Jamf Pro when the invitation is created but **never persisted in Terraform state**. Jamf Pro does not return the plaintext on refresh, so the provider treats it as write-only. Pair it with `ssh_password_wo_version`. Changing this forces replacement.",
				Optional:            true,
				Sensitive:           true,
				WriteOnly:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"ssh_password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "Rotation companion for the `WriteOnly` `ssh_password`. Because this invitation cannot be updated in place, any change to this value (like any other attribute) forces a replace that re-sends the current `ssh_password`. Set it to `1` initially and bump it to rotate. Changing this forces replacement.",
				Optional:            true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"invitation_status": schema.StringAttribute{
				MarkdownDescription: "Current status of the invitation, returned by Jamf Pro (e.g. `PENDING`, `MULTIPLE_USES`).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"times_used": schema.Int64Attribute{
				MarkdownDescription: "Number of times the invitation has been used, returned by Jamf Pro.",
				Computed:            true,
			},
			"invited_user_uuid": schema.StringAttribute{
				MarkdownDescription: "UUID of the invited user, returned by Jamf Pro.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

// Configure wires the Jamf ProClassic client into the resource via the shared
// providerdata.ConfigureProClassic helper.
func (r *ComputerInvitationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := providerdata.ConfigureProClassic(ctx, req.ProviderData, minJamfProVersion, "jamfplatform_pro_computer_invitation")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.client = client
}

// ImportState handles import by the Jamf Pro computer invitation numeric ID.
func (r *ComputerInvitationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
